version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - gocritic
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
    - unconvert
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: errors
              desc: Use github.com/sourcegraph/sourcegraph/lib/errors instead
            - pkg: github.com/pkg/errors
              desc: Use github.com/sourcegraph/sourcegraph/lib/errors instead
            - pkg: github.com/cockroachdb/errors
              desc: Use github.com/sourcegraph/sourcegraph/lib/errors instead
            - pkg: github.com/hashicorp/go-multierror
              desc: Use github.com/sourcegraph/sourcegraph/lib/errors instead
            - pkg: io/ioutil
              desc: The ioutil package has been deprecated
    forbidigo:
      forbid:
        - pattern: fmt\.Errorf
    gocritic:
      disabled-checks:
        - appendAssign
        - assignOp
        - commentFormatting
        - deprecatedComment
        - exitAfterDefer
        - ifElseChain
        - singleCaseSwitch
    govet:
      disable:
        - composites
    staticcheck:
      checks:
        - all
        - -QF1001 # De Morgan's law simplifications
        - -QF1008 # Embedded field selector simplifications
        - -ST1003 # Naming conventions (ID vs Id, URL vs Url, etc.)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
