# See explanation of linters at https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unused

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - errors: 'Use github.com/sourcegraph/sourcegraph/lib/errors instead'
      - github.com/pkg/errors: 'Use github.com/sourcegraph/sourcegraph/lib/errors instead'
      - github.com/cockroachdb/errors: 'Use github.com/sourcegraph/sourcegraph/lib/errors instead'
      - github.com/hashicorp/go-multierror: 'Use github.com/sourcegraph/sourcegraph/lib/errors instead'
      - io/ioutil: 'The ioutil package has been deprecated'
  gocritic:
    disabled-checks:
      - appendAssign # Too many false positives
      - assignOp # Maybe worth adding, but likely not worth the noise
      - commentFormatting # No strong benefit
      - deprecatedComment # Unnecessary
      - exitAfterDefer # Only occurs in auxiliary tools
      - ifElseChain # Noisy for not much gain
      - singleCaseSwitch # Noisy for not much gain
  govet:
    disable:
      - composites
  forbidigo:
    forbid:
      # Use errors.New instead
      - 'fmt\.Errorf'

issues:
  exclude-rules:
    # Exclude bodyclose lint from tests because leaking connections in tests
    # is a non-issue, and checking that adds unnecessary noise
    - path: _test\.go
      linters:
        - bodyclose

run:
  timeout: 5m
