version: "{build}"
shallow_clone: true
clone_folder: c:\gopath\src\github.com\sourcegraph\src-cli
environment:
  GOPATH: c:\gopath
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -t -v ./...
build_script:
  - go test -v ./...
