// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: marionette.proto

// TODO: figure out how to import and use google.rpc.Status.

package marionette

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChangesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modified []string `protobuf:"bytes,1,rep,name=modified,proto3" json:"modified,omitempty"`
	Added    []string `protobuf:"bytes,2,rep,name=added,proto3" json:"added,omitempty"`
	Deleted  []string `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	Renamed  []string `protobuf:"bytes,4,rep,name=renamed,proto3" json:"renamed,omitempty"`
}

func (x *ChangesResponse) Reset() {
	*x = ChangesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marionette_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesResponse) ProtoMessage() {}

func (x *ChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marionette_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangesResponse.ProtoReflect.Descriptor instead.
func (*ChangesResponse) Descriptor() ([]byte, []int) {
	return file_marionette_proto_rawDescGZIP(), []int{0}
}

func (x *ChangesResponse) GetModified() []string {
	if x != nil {
		return x.Modified
	}
	return nil
}

func (x *ChangesResponse) GetAdded() []string {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *ChangesResponse) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *ChangesResponse) GetRenamed() []string {
	if x != nil {
		return x.Renamed
	}
	return nil
}

type DiffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diff []byte `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marionette_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marionette_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_marionette_proto_rawDescGZIP(), []int{1}
}

func (x *DiffResponse) GetDiff() []byte {
	if x != nil {
		return x.Diff
	}
	return nil
}

type UnzipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *UnzipRequest) Reset() {
	*x = UnzipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marionette_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnzipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnzipRequest) ProtoMessage() {}

func (x *UnzipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marionette_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnzipRequest.ProtoReflect.Descriptor instead.
func (*UnzipRequest) Descriptor() ([]byte, []int) {
	return file_marionette_proto_rawDescGZIP(), []int{2}
}

func (x *UnzipRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_marionette_proto protoreflect.FileDescriptor

var file_marionette_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0f, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64,
	0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x69, 0x66, 0x66, 0x22, 0x22, 0x0a, 0x0c, 0x55, 0x6e, 0x7a, 0x69,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x32, 0x84, 0x02, 0x0a,
	0x0a, 0x4d, 0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b,
	0x2e, 0x6d, 0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x04, 0x44, 0x69, 0x66, 0x66, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e,
	0x6d, 0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x07, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x05, 0x55, 0x6e, 0x7a, 0x69, 0x70, 0x12,
	0x18, 0x2e, 0x6d, 0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x2e, 0x55, 0x6e, 0x7a,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2f, 0x73, 0x72,
	0x63, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d,
	0x61, 0x72, 0x69, 0x6f, 0x6e, 0x65, 0x74, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_marionette_proto_rawDescOnce sync.Once
	file_marionette_proto_rawDescData = file_marionette_proto_rawDesc
)

func file_marionette_proto_rawDescGZIP() []byte {
	file_marionette_proto_rawDescOnce.Do(func() {
		file_marionette_proto_rawDescData = protoimpl.X.CompressGZIP(file_marionette_proto_rawDescData)
	})
	return file_marionette_proto_rawDescData
}

var file_marionette_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_marionette_proto_goTypes = []interface{}{
	(*ChangesResponse)(nil), // 0: marionette.ChangesResponse
	(*DiffResponse)(nil),    // 1: marionette.DiffResponse
	(*UnzipRequest)(nil),    // 2: marionette.UnzipRequest
	(*empty.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_marionette_proto_depIdxs = []int32{
	3, // 0: marionette.Marionette.Changes:input_type -> google.protobuf.Empty
	3, // 1: marionette.Marionette.Diff:input_type -> google.protobuf.Empty
	3, // 2: marionette.Marionette.Prepare:input_type -> google.protobuf.Empty
	2, // 3: marionette.Marionette.Unzip:input_type -> marionette.UnzipRequest
	0, // 4: marionette.Marionette.Changes:output_type -> marionette.ChangesResponse
	1, // 5: marionette.Marionette.Diff:output_type -> marionette.DiffResponse
	3, // 6: marionette.Marionette.Prepare:output_type -> google.protobuf.Empty
	3, // 7: marionette.Marionette.Unzip:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marionette_proto_init() }
func file_marionette_proto_init() {
	if File_marionette_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marionette_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marionette_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marionette_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnzipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marionette_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marionette_proto_goTypes,
		DependencyIndexes: file_marionette_proto_depIdxs,
		MessageInfos:      file_marionette_proto_msgTypes,
	}.Build()
	File_marionette_proto = out.File
	file_marionette_proto_rawDesc = nil
	file_marionette_proto_goTypes = nil
	file_marionette_proto_depIdxs = nil
}
