# For more information, refer to the "Dependent Docker images" section of
# DEVELOPMENT.md.
name: Publish Docker image dependencies

# We only want to build on releases; this condition is 100% stolen from the
# goreleaser action.
on:
  - push
  # push:
  #   tags:
  #     - "*"
  #     - "!latest"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - run: ./docker/campaign-volume-workspace/push.py -d ./docker/campaign-volume-workspace/Dockerfile -i sourcegraph/src-campaign-volume-workspace
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: sourcegraphci
