# For more information, refer to the "Dependent Docker images" section of
# DEVELOPMENT.md.
name: Publish Docker image dependencies

# We only want to build on releases; this condition is 100% stolen from the
# goreleaser action.
on:
  push:
    tags:
      - "*"
      - "!latest"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # We need buildx to be able to build a multi-architecture image.
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      # We also need QEMU, since this is running on an AMD64 host and we want to
      # build ARM64 images.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - run: ./docker/batch-change-volume-workspace/push.py -d ./docker/batch-change-volume-workspace/Dockerfile -i sourcegraph/src-batch-change-volume-workspace -p linux/amd64,linux/arm64,linux/386
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: sourcegraphci

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: sourcegraphci
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sourcegraph/src-batch-change-volume-workspace
          readme-filepath: ./docker/batch-change-volume-workspace/README.md
