name: Run go tests

on:
  - push
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - run: go get -d -t ./...
      - run: go test -i ./...
      - run: go test -race -v ./...
