name: GoReleaser

on:
  push:
    tags:
      - '*'
      - '!latest'

jobs:
  goreleaser:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go get -d -t ./...
      - run: go test -i ./...
      - run: go test -race -v ./...
      - run: echo "${DOCKER_PASSWORD}" | docker login -u=sourcegraphci --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          # Use separate access token, because we need a scope:repo token to publish the brew formula.
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  npm:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm publish --access public
        working-directory: npm-distribution
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
