name: SCIP
on:
  workflow_dispatch:
  push:
env:
  GOPRIVATE: "github.com/sourcegraph/*"
  PRIVATE_TOKEN: "${{ secrets.PRIVATE_SG_ACCESS_TOKEN }}"
jobs:
  scip-go:
    runs-on: ubuntu-latest
    container: sourcegraph/scip-go
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Set directory to safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Build src-cli
        run: go build -o ./src-cli ./cmd/src

      - name: Enable pulling Go modules from private sourcegraph/sourcegraph
        run: git config --global url."https://${PRIVATE_TOKEN}@github.com/sourcegraph/".insteadOf "https://github.com/sourcegraph/"

      - name: Generate SCIP data
        run: scip-go

      - name: Upload SCIP to Cloud
        run: ./src-cli code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DOTCOM }}

      - name: Upload SCIP to S2
        run: ./src-cli code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}

      - name: Compress SCIP file
        run: gzip index.scip

      - name: Upload compressed SCIP to Cloud
        run: ./src-cli code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_DOTCOM }}

      - name: Upload compressed SCIP to S2
        run: ./src-cli code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress
        env:
          SRC_ENDPOINT: https://sourcegraph.sourcegraph.com/
          SRC_ACCESS_TOKEN: ${{ secrets.SRC_ACCESS_TOKEN_S2 }}
